site_name: My Docs
theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: true 

nav:
  - Home: index.md
  - "Core Modules":
    - "analyticsdb.py": "analyticsdb.md"
    - "config.py": "config.md"